Illarion\DatabaseBundle\Entity\Accounts\Account:
    type: entity
    table: account
    schema: accounts
    uniqueConstraints:
        acc_name_idx:
            columns: [ accLogin ]
        acc_email_idx:
            columns: [ accEmail ]
    indexes:
        acc_name_password_idx:
            columns: [ accLogin, accPasswd ]
    id:
        accId:
            type: integer
            id: true
            column: acc_id
            generator:
                strategy: SEQUENCE
            sequenceGenerator:
                sequenceName: accounts.account_seq
                allocationSize: 10
                initialValue: 1
    fields:
        accLogin:
            type: string
            length: '50'
            column: acc_login
            nullable: false
        accPasswd:
            type: string
            length: '50'
            column: acc_passwd
            nullable: false
        accEmail:
            type: string
            length: '50'
            column: acc_email
            nullable: true
        accRegisterdate:
            type: datetime
            column: acc_registerdate
            nullable: false
        accLastip:
            type: string
            length: '39'
            column: acc_lastip
            nullable: false
        accState:
            type: integer
            column: acc_state
            nullable: false
        accMaxchars:
            type: integer
            column: acc_maxchars
            nullable: false
        accLang:
            type: smallint
            column: acc_lang
            nullable: false
    oneToMany:
        illarionServerChars:
            targetEntity: Illarion\DatabaseBundle\Entity\IllarionServer\Chars
            mappedBy: account
        testServerChars:
            targetEntity: Illarion\DatabaseBundle\Entity\TestServer\Chars
            mappedBy: account
        devServerChars:
            targetEntity: Illarion\DatabaseBundle\Entity\DevServer\Chars
            mappedBy: account
    lifecycleCallbacks: {  }
